{ config, pkgs, lib, ... }:

# Bootstraps Flux from the machine layer, so the cluster populates itself.
#
# k3s applies anything under /var/lib/rancher/k3s/server/manifests at startup,
# and services.k3s.manifests links files there declaratively. So the chain is:
#
#   nixos-rebuild switch -> k3s starts -> k3s applies Flux -> Flux reads the
#   repo -> apps exist
#
# Nobody runs kubectl. A fresh box, or the second dev's box, reaches a populated
# cluster from one command. That is the reproducibility this is for -- not
# elaborate machinery.
#
# Deliberately NOT `flux bootstrap`: that wants provider write scope so it can
# push a commit and create a deploy key. The manifests it would commit are
# already here. A public source needs no credential; a private one names a
# separately provisioned read credential with secretRef.
#
# source-controller, kustomize-controller, helm-controller and
# notification-controller are installed. helm-controller was added when the
# monitoring stack needed it -- kube-prometheus-stack is a Helm chart and there
# is no sensible plain-manifest equivalent. notification-controller has nothing
# to act on: nothing under cluster/ declares an Alert, a Provider or a Receiver.
#
# Note which layer this file belongs to. The controllers and the objects below
# are applied by k3s auto-deploy, not by Flux, so changing either is a
# nixos-rebuild -- not something Flux picks up from git on its own.
#
# WHY THE SYNC OBJECTS ARE GENERATED HERE rather than kept as a checked-in
# manifest, which is what they were. Which repository a host follows, and on
# what branch, is exactly the kind of thing an adopting machine has to be able
# to state -- a second box bringing itself up against a branch is the ordinary
# case, not an exotic one. Holding it in a committed YAML made it a property of
# the repository instead of a property of the host, and the only way to change
# it was to edit a file every host reads. The controller install stays a
# checked-in file: it is a vendored upstream artifact, identical on every
# adopter, and generating it would mean owning a copy of Flux's installer.
#
# THAT REASON COVERS THE TWO SOURCES AND ONE ROOT, AND STOPS THERE.
# `fabric-release` is `fabric` read again -- the same repository, branch,
# interval and credential -- with `spec.ignore` keeping only the files under
# cluster/chuggy-migrate/ and cluster/chuggy/, so it is a host's to state for
# the reason `fabric` is. No Kustomization reads it. The root applies a
# directory of `fabric`, cluster/flux/, and every Kustomization that reads
# that source is declared there, a layer each. What a layer applies,
# what it depends on and how its health is read are the same on every host that
# follows the repository, and generated here each would change by a rebuild of
# every box instead of by a commit.
#
# THE OBJECT NAMES ARE NOT OPTIONS, here or in cluster/flux/. Nothing under
# cluster/ reads the label -- what reads `kustomize.toolkit.fluxcd.io/name` by
# value is the README and whoever is standing in front of the cluster, telling
# what this repo owns from what the rehearsal's second control loop put there.
# The value is the name of the Kustomization that applied the object:
# `chuggy-migrate` or `chuggy` on a chuggy release's objects, `apps` on what
# cluster/apps/ declares. That is enough to make each name a contract rather
# than a setting: a change to one would be telling the truth to Flux and a lie
# to every reader.

let
  cfg = config.chuggy.flux;

  # Empty for a public source, and both sources below carry the same one.
  secretRef = lib.optionalString (cfg.secretRef != null)
    "  secretRef:\n    name: ${cfg.secretRef}\n";

  # Named for the manifest k3s auto-deploy is given below, so the store path and
  # the file that lands in the manifests directory are one name, not two.
  syncManifest = pkgs.writeText "flux-sync.yaml" ''
    # Generated by modules/flux.nix. Editing the objects in the cluster is undone
    # by the next k3s start; edit the host's chuggy.flux options instead.
    #
    # Public sources omit secretRef. Private sources name a Secret provisioned
    # independently of this generated manifest; credential bytes must never be
    # interpolated into a Nix store path.
    ---
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: fabric
      namespace: flux-system
    spec:
      interval: ${cfg.sourceInterval}
      url: ${cfg.repositoryUrl}
      ref:
        branch: ${cfg.branch}
    ${secretRef}
    ---
    # source-controller decides a path by the last of these lines that matches
    # it: the first excludes every path, and each of the others keeps the files
    # under one directory. tests/flux-release-source.py holds what they keep
    # against this repository's own tree.
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: fabric-release
      namespace: flux-system
    spec:
      interval: ${cfg.sourceInterval}
      url: ${cfg.repositoryUrl}
      ref:
        branch: ${cfg.branch}
    ${secretRef}
      ignore: |
        /*
        !/cluster/chuggy-migrate/
        !/cluster/chuggy/
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: fabric
      namespace: flux-system
    spec:
      interval: ${cfg.interval}
      path: ${cfg.path}
      sourceRef:
        kind: GitRepository
        name: fabric
      # A layer whose declaration leaves the path is deleted, and what it had
      # applied goes by that layer's own deletionPolicy.
      prune: true
      # The path holds Kustomization objects and nothing else. Waiting on them
      # would make this one unready whenever any layer is, and `builds` is
      # unready for as long as a failed BuildRun stays declared.
      wait: false
      # k3s deletes an object that leaves this manifest. The default policy
      # mirrors `prune`, so this object deleted would delete every layer, and a
      # layer deleted deletes what it applied unless it orphans as well.
      # Pruning at reconcile is unaffected.
      deletionPolicy: Orphan
      timeout: ${cfg.timeout}
  '';
in
{
  options.chuggy.flux = {
    enable = lib.mkEnableOption "Flux GitOps reconciliation";

    repositoryUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "https://github.com/gdoteof/chuggy-fabric.git";
      description = ''
        Repository Flux reconciles this cluster from. Required. For a private
        source, provision its credential before Flux starts and name that
        Secret with chuggy.flux.secretRef.
      '';
    };

    branch = lib.mkOption {
      type = lib.types.str;
      default = "main";
      description = ''
        Branch Flux follows. Pushing to it is a live cluster change, which is
        why this is a per-host input: a box being brought up, or one being used
        to try a change, should be able to follow something other than whatever
        the shared branch holds at that moment.
      '';
    };

    secretRef = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "fabric-source-auth";
      description = ''
        Name of a Secret in flux-system containing authentication and, where
        required, TLS trust material for repositoryUrl. The host operator must
        provision it before selecting a private source. The value names a
        Secret only; credential material must not enter Nix configuration or
        the Nix store.
      '';
    };

    path = lib.mkOption {
      type = lib.types.str;
      default = "./cluster/flux";
      description = ''
        Directory inside the repository declaring the layers, one Flux
        Kustomization object each and nothing else. The root applies it; each
        layer names the directory it applies.
      '';
    };

    sourceInterval = lib.mkOption {
      type = lib.types.str;
      default = "1m";
      description = "How often source-controller re-fetches the branch.";
    };

    interval = lib.mkOption {
      type = lib.types.str;
      default = "5m";
      description = ''
        How often kustomize-controller reapplies the layer declarations under
        path. How often a layer reapplies its own directory is that layer's
        interval, in the declaration.
      '';
    };

    timeout = lib.mkOption {
      type = lib.types.str;
      default = "3m";
      description = ''
        How long one apply of the layer declarations may take before it is
        reported failed. The root waits on nothing, so no layer's health is
        inside it.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.repositoryUrl != null;
        message = ''
          chuggy.flux.enable is on but chuggy.flux.repositoryUrl is unset.
          Name the repository this host reconciles its cluster from; Flux
          installed with nothing to follow is a set of idle controllers and an
          empty cluster that reports no error.
        '';
      }
      {
        assertion = cfg.secretRef == null || cfg.secretRef != "";
        message = ''
          chuggy.flux.secretRef is empty. Omit it for an anonymous source or
          name the credential Secret already provisioned in flux-system.
        '';
      }
    ];

    services.k3s.manifests = {
      # Order matters on a cold start: the CRDs and controllers must exist
      # before the GitRepositories and Kustomization that use them. k3s applies
      # these alphabetically, and "components" sorts before "sync" -- which is
      # load-bearing, not a coincidence. If that ever stops holding, the sync
      # objects fail once and k3s retries them, so it self-corrects either way.
      flux-components.source = ../cluster/flux-system/gotk-components.yaml;
      flux-sync.source = syncManifest;
    };

    # `flux` CLI for inspecting reconciliation: flux get kustomizations, etc.
    environment.systemPackages = [ pkgs.fluxcd ];
  };
}
