{ config, pkgs, lib, ... }:

# Bootstraps Flux from the machine layer, so the cluster populates itself.
#
# k3s applies anything under /var/lib/rancher/k3s/server/manifests at startup,
# and services.k3s.manifests links files there declaratively. So the chain is:
#
#   nixos-rebuild switch -> k3s starts -> k3s applies Flux -> Flux reads the
#   repo -> apps exist
#
# Nobody runs kubectl. A fresh box, or the second dev's box, reaches a populated
# cluster from one command. That is the reproducibility this is for -- not
# elaborate machinery.
#
# Deliberately NOT `flux bootstrap`: that wants provider write scope so it can
# push a commit and create a deploy key. The manifests it would commit are
# already here. A public source needs no credential; a private one names a
# separately provisioned read credential with secretRef.
#
# source-controller, kustomize-controller and helm-controller are installed.
# helm-controller was added when the monitoring stack needed it -- kube-prometheus-
# stack is a Helm chart and there is no sensible plain-manifest equivalent.
# notification-controller is still omitted; nothing alerts outward yet.
#
# Note which layer this file belongs to. The controllers and the objects below
# are applied by k3s auto-deploy, not by Flux, so changing either is a
# nixos-rebuild -- not something Flux picks up from git on its own.
#
# WHY THE SYNC OBJECTS ARE GENERATED HERE rather than kept as a checked-in
# manifest, which is what they were. Which repository a host follows, and on
# what branch, is exactly the kind of thing an adopting machine has to be able
# to state -- a second box bringing itself up against a branch is the ordinary
# case, not an exotic one. Holding it in a committed YAML made it a property of
# the repository instead of a property of the host, and the only way to change
# it was to edit a file every host reads. The controller install stays a
# checked-in file: it is a vendored upstream artifact, identical on every
# adopter, and generating it would mean owning a copy of Flux's installer.
#
# THE OBJECT NAMES ARE NOT OPTIONS. Nothing in cluster/apps/ reads the label --
# what reads `kustomize.toolkit.fluxcd.io/name: apps` by value is the README and
# whoever is standing in front of the cluster, telling what this repo owns from
# what the rehearsal's second control loop put there. That is enough to make the
# name a contract rather than a setting: a host that changed it would be telling
# the truth to Flux and a lie to every reader.

let
  cfg = config.chuggy.flux;

  # Named for the manifest k3s auto-deploy is given below, so the store path and
  # the file that lands in the manifests directory are one name, not two.
  syncManifest = pkgs.writeText "flux-sync.yaml" ''
    # Generated by modules/flux.nix. Editing the objects in the cluster is undone
    # by the next k3s start; edit the host's chuggy.flux options instead.
    #
    # Public sources omit secretRef. Private sources name a Secret provisioned
    # independently of this generated manifest; credential bytes must never be
    # interpolated into a Nix store path.
    ---
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: fabric
      namespace: flux-system
    spec:
      interval: ${cfg.sourceInterval}
      url: ${cfg.repositoryUrl}
      ref:
        branch: ${cfg.branch}
${lib.optionalString (cfg.secretRef != null) ''      secretRef:
        name: ${cfg.secretRef}
''}
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: apps
      namespace: flux-system
    spec:
      interval: ${cfg.interval}
      # kustomize-controller synthesises a kustomization when the path has none
      # and obeys the one it finds when it does -- which is the case that
      # bites. A directory carrying a kustomization.yaml applies exactly its
      # `resources:` list, so a manifest dropped into the directory and not
      # added to that list is one this Kustomization stops applying, and
      # `prune` below then deletes what it had applied before.
      path: ${cfg.path}
      sourceRef:
        kind: GitRepository
        name: fabric
      # Deleting a file deletes the resource. Without this, removals in git are
      # silently ignored and the cluster accumulates things nobody declared.
      prune: ${lib.boolToString cfg.prune}
      wait: true
      timeout: ${cfg.timeout}
  '';
in
{
  options.chuggy.flux = {
    enable = lib.mkEnableOption "Flux GitOps reconciliation";

    repositoryUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "https://github.com/gdoteof/chuggy-fabric.git";
      description = ''
        Repository Flux reconciles this cluster from. Required. For a private
        source, provision its credential before Flux starts and name that
        Secret with chuggy.flux.secretRef.
      '';
    };

    branch = lib.mkOption {
      type = lib.types.str;
      default = "main";
      description = ''
        Branch Flux follows. Pushing to it is a live cluster change, which is
        why this is a per-host input: a box being brought up, or one being used
        to try a change, should be able to follow something other than whatever
        the shared branch holds at that moment.
      '';
    };

    secretRef = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "fabric-source-auth";
      description = ''
        Name of a Secret in flux-system containing authentication and, where
        required, TLS trust material for repositoryUrl. The host operator must
        provision it before selecting a private source. The value names a
        Secret only; credential material must not enter Nix configuration or
        the Nix store.
      '';
    };

    path = lib.mkOption {
      type = lib.types.str;
      default = "./cluster/apps";
      description = "Directory inside the repository holding the desired cluster state.";
    };

    sourceInterval = lib.mkOption {
      type = lib.types.str;
      default = "1m";
      description = "How often source-controller re-fetches the branch.";
    };

    interval = lib.mkOption {
      type = lib.types.str;
      default = "5m";
      description = ''
        How often kustomize-controller reapplies the directory. This is the
        window a hand-run kubectl change survives in, which matters more than it
        sounds: a repair applied by hand inside it is undone without an error.
      '';
    };

    timeout = lib.mkOption {
      type = lib.types.str;
      default = "3m";
      description = "How long one reconciliation may take before it is reported failed.";
    };

    prune = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Whether deleting a file deletes the resource. On, because the
        alternative is a cluster that accumulates objects nobody declares and
        still reports itself reconciled.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.repositoryUrl != null;
        message = ''
          chuggy.flux.enable is on but chuggy.flux.repositoryUrl is unset.
          Name the repository this host reconciles its cluster from; Flux
          installed with nothing to follow is a set of idle controllers and an
          empty cluster that reports no error.
        '';
      }
      {
        assertion = cfg.secretRef == null || cfg.secretRef != "";
        message = ''
          chuggy.flux.secretRef is empty. Omit it for an anonymous source or
          name the credential Secret already provisioned in flux-system.
        '';
      }
    ];

    services.k3s.manifests = {
      # Order matters on a cold start: the CRDs and controllers must exist
      # before the GitRepository and Kustomization that use them. k3s applies
      # these alphabetically, and "components" sorts before "sync" -- which is
      # load-bearing, not a coincidence. If that ever stops holding, the sync
      # objects fail once and k3s retries them, so it self-corrects either way.
      flux-components.source = ../cluster/flux-system/gotk-components.yaml;
      flux-sync.source = syncManifest;
    };

    # `flux` CLI for inspecting reconciliation: flux get kustomizations, etc.
    environment.systemPackages = [ pkgs.fluxcd ];
  };
}
